language: go

# Needed for e2e tests
sudo: true
go: 1.9.x
go_import_path: github.com/kubernetes-csi/drivers
install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure -vendor-only
  - make hostpath
script:
- go fmt $(go list ./... | grep -v vendor) | wc -l | grep 0
- go vet $(go list ./... | grep -v vendor)
- go test $(go list ./... | grep -v vendor)
- ./hack/e2e-hostpath.sh
